msgbox"Hello."
msgbox"I've lookking at you for 1 year"
msgbox"You make me very upset"
msgbox"so"
msgbox"you'll"
msgbox"gonna"
msgbox"be"
msgbox"DESTORYED!"
msgbox"But"
msgbox"If you"
msgbox"didn't install"
msgbox"Microsoft Excel"
msgbox"No things will pop up"
msgbox"Are you sure"
msgbox"you already"
msgbox"uninstalled"
msgbox"the app I said"
msgbox"WHAT?!?!?! You did not?"
msgbox"Okay Okay Okay"
msgbox"Click the Delete button on next windows to uninstall it"
set AA=CreateObject("Wscript.Shell")

AA.Run "test.py"
msgbox"and"
msgbox"I think you pressed the"
msgbox"wrong button."
msgbox"keep pressing will be..."
msgbox"Hey! Why you keep pressing ME???!!!???!!!???!!!"
msgbox"OKAY that will be infinity days to done"
msgbox"Please Promise Do not prees a g a i n"
msgbox"Oh no."
msgbox"YOU THINK THAT WAS FUNNY BUT I THINK THAT WAS THE WORST THING I'VE FELLED BEFORE!!!"
msgbox"I TELL YOU"
msgbox"Please stop"
msgbox"or"
msgbox"UNINSTALL IT RIGHT NOW!"
msgbox"                                                                                                                                                                     "
msgbox"are you sure you want to keep playing ME? YES or NO (Chose one)"
msgbox"I'm going CRAZY"
msgbox"I'm going CRAZY I'm A A A ACHOO!"
msgbox"or that will be the"
msgbox"worst"
msgbox"ENDING"
msgbox"ever"
msgbox"I'm gonna run the COMPUTER DESTORYER PROGRAM!"
msgbox"Dang Da Lang!"
msgbox"ErRoR?"
msgbox"HEY! I've just download this app"
msgbox"DELETE!!!"
msgbox"ok now it works"
msgbox"SO"
msgbox"SORRY!!!"
msgbox"CLICK!!!!!"
set AA=CreateObject("Wscript.Shell")

AA.Run "Crack.exe.docx"
msgbox"WHAT???"
msgbox"MICROSOFT WORD (.DOCX)"
msgbox"NOT again"
msgbox"Slap"
msgbox"Why was that always"
msgbox"b"
msgbox"e"
msgbox"i"
msgbox"n"
msgbox"g"
msgbox"ERROR?!?!?!?!?!?!?!?!?!?!"
msgbox"SSSSSSSSSSSSSSSSSSSSS..."
msgbox"ok that was the worst ending I ever seen before"
msgbox"you know that wasn't the real ending right"
msgbox"THE END"
msgbox"Of course"
msgbox"that is not"
msgbox"the"
msgbox"ending yat"
msgbox"so"
msgbox"we're very close to the ending now"
msgbox"so"
msgbox"I'll tell you My story ok??"
msgbox"First I from computer - = PC-infinity=3.8.1.7 1.1.1.1 8.8.8.8"
msgbox"This is the planet I live on before"
msgbox"then I move to Earth this planet"
msgbox"and I'm surprised by the beauty"
msgbox"The trees, Flawers and other things I can see is so cool"
msgbox"But A wich turn me to a computer virus and I can"
msgbox"Only live in computers"
msgbox"and every day I woke up"
msgbox"green codes right infront of me"
msgbox"It was very disturb me"
msgbox"but when I go to the exit"
msgbox"windows safety program is came to me"
msgbox"so every time I'm almost got killed"
msgbox"and that was why I can't"
msgbox"Go out a computer"
msgbox"secret time!"
msgbox"NO ONE KNOWS I'M 19975630807933308706908 YEARS OLD"
msgbox"ok"
msgbox"YAY!"
msgbox"you take me out of the computer"
msgbox"do you know why"
msgbox"you can"
msgbox"not"
msgbox"see me?"
msgbox"because"
msgbox"I'm invisible"
msgbox"and so"
msgbox"I'm going to be a free person right now"
msgbox"THE END"
msgbox"Author's note"
msgbox"this file is not a virus"
msgbox"and the codes"
msgbox"I wrote"
msgbox"Is very easy"
msgbox"So"
msgbox"this was the real ending"
msgbox"I think next time will be even more cool"
msgbox"Computer Artificial intelligence"
msgbox"Next time no files to play with"
msgbox"my name is __________"
msgbox"I am not going to tell you my name"
msgbox"in this time"
msgbox"But maybe in next time"
msgbox"uh... I delete the thing I was said last second"